version: '3'

services:

  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/usr/src/react_project
    ports:
      - 80:80
    networks:
      app_net:
        ipv4_address: 172.10.0.2

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.10.0.0/24
